# Generated by Django 5.1.1 on 2024-11-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(default=1),
        ),
    ]
