# Generated by Django 5.1.1 on 2024-11-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0002_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
