# Generated by Django 5.1.1 on 2024-12-23 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0005_remove_agent_email_remove_agent_user_agent_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.AddField(
            model_name='client',
            name='aadhar_card',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='agent_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='agent_visited_policy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='claim_satisfaction',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_preferences',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_service_satisfaction',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='existing_profile_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='income_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='insurance_markup_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pan_card',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='presence_of_kids',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='clients/'),
        ),
        migrations.AddField(
            model_name='client',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='source_of_information',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='willingness_to_purchase',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='willingness_to_share',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='willingness_to_switch',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='agents/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='alerted_agents',
            field=models.ManyToManyField(null=True, related_name='campaigns', to='insurapp.agent'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='basic_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(null=True, upload_to='campaign_images/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='insurapp.agent'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
