# Generated by Django 5.1.1 on 2024-12-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0007_agent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='alerted_agents',
        ),
        migrations.AddField(
            model_name='campaign',
            name='assigned_agents',
            field=models.ManyToManyField(to='insurapp.agent'),
        ),
    ]
