# Generated by Django 5.1.1 on 2024-12-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0008_remove_campaign_alerted_agents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='assigned_agents',
            field=models.ManyToManyField(null=True, related_name='campaigns', to='insurapp.agent'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_images/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
