# Generated by Django 5.1.1 on 2024-12-24 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0009_campaign_campaign_id_alter_campaign_assigned_agents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='agents/'),
        ),
    ]
