# Generated by Django 5.1.1 on 2024-12-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0010_agent_user_alter_agent_agent_id_alter_agent_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='agents',
            field=models.ManyToManyField(blank=True, to='insurapp.agent'),
        ),
    ]
