# Generated by Django 5.1.1 on 2024-12-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0011_campaign_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.IntegerField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
