# Generated by Django 5.1.1 on 2024-12-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0012_alter_campaign_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Agent'), (3, 'Other')]),
        ),
    ]
