# Generated by Django 5.1.1 on 2024-12-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Agent')], default=2),
        ),
    ]
