# Generated by Django 5.1.1 on 2024-12-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0015_alter_campaign_campaign_id_alter_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='assigned_agents',
            field=models.ManyToManyField(related_name='campaigns', to='insurapp.agent'),
        ),
    ]
