# Generated by Django 5.1.1 on 2024-12-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0017_alter_client_aadhar_card_alter_client_agent_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
