# Generated by Django 5.1.1 on 2024-12-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0019_alter_client_agent_alter_client_presence_of_kids_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='aadhar_card',
            new_name='aadhar_number',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='pan_card',
            new_name='pan_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='location',
        ),
        migrations.AddField(
            model_name='client',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='employment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='insurance_interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='number_of_dependents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='insurapp.agent'),
        ),
    ]
