# Generated by Django 5.1.1 on 2024-12-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0022_alter_client_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='agents',
        ),
    ]
