# Generated by Django 5.1.1 on 2024-12-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0023_remove_campaign_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
