# Generated by Django 5.1.1 on 2024-12-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0024_alter_campaign_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
