# Generated by Django 5.1.1 on 2024-12-31 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0026_remove_campaign_assigned_agents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='agent_id',
        ),
    ]
