# Generated by Django 5.1.1 on 2024-12-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0027_remove_campaign_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='assigned_agents',
            field=models.ManyToManyField(related_name='assigned_campaigns', through='insurapp.CampaignAssignment', to='insurapp.agent'),
        ),
    ]
