# Generated by Django 5.1.1 on 2025-01-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0029_alter_campaignassignment_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Agent')], default=1),
        ),
    ]
