# Generated by Django 5.1.1 on 2025-01-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0030_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurapp.campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurapp.client')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='clients',
            field=models.ManyToManyField(related_name='campaigns', through='insurapp.ClientCampaign', to='insurapp.client'),
        ),
    ]
