# Generated by Django 5.1.1 on 2025-01-06 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0031_clientcampaign_campaign_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcampaign',
            name='enrollment_date',
        ),
        migrations.AddField(
            model_name='clientcampaign',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurapp.agent'),
        ),
    ]
