# Generated by Django 5.1.1 on 2025-01-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurapp', '0032_remove_clientcampaign_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
